### ISSUE TITLE
Where can I find information about "The implementation of MSWeakTimer was reviewed and" Validated by a libdispatch. GCD) engineer at the WWDC 2013 Core OS Lab. "? 

### ISSUE THREAD

**Issue by ghost** [mindsnacks/MSWeakTimer#29]
Where can I find information about "The implementation of MSWeakTimer was reviewed and" Validated by a libdispatch. GCD) engineer at the WWDC 2013 Core OS Lab. "? Could you give me a link?

**Comment by JaviSoto** [comment]
Hey!

That just means that I had a conversation with some GCD engineers then and they helped me make sure that my implementation was correct. There's no link I can provide.

That been said, this library is not that useful anymore, I recommend using the block-based `NSTimer` API introduced in iOS 10, and capturing references to `self` weakly in the blocks.

**Comment by Zhang1Peng** [comment]
Thanks very much！

张鹏-----------------------------------------------------------------------------手机：15810746400邮箱：zhangpeng.0304@aliyun.comQQ ：296197662
------------------------------------------------------------------发件人：Javier Soto <notifications@github.com>发送时间：2018年2月2日(星期五) 06:21收件人：mindsnacks/MSWeakTimer <MSWeakTimer@noreply.github.com>抄　送：zhangPeng丶 <zhangpeng.0304@aliyun.com>; Author <author@noreply.github.com>主　题：Re: [mindsnacks/MSWeakTimer] Where can I find information about "The implementation of MSWeakTimer was reviewed and" Validated by a libdispatch. GCD) engineer at the WWDC 2013 Core OS Lab. "? (#29)
Hey!
That just means that I had a conversation with some GCD engineers then and they helped me make sure that my implementation was correct. There's no link I can provide.
That been said, this library is not that useful anymore, I recommend using the block-based NSTimer API introduced in iOS 10, and capturing references to self weakly.

**Comment by ghost** [comment]
Thanks very much！
